{
 "title": "任务资源详情页",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "容器名",
    "query": {
     "query": "label_values(container_fs_usage_bytes{namespace=\"default\"}, container)"
    }
   },
   {
    "name": "deployment",
    "label": "任务名",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace=\"default\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "label": "罐子名",
    "query": {
     "query": "label_values(container_fs_usage_bytes{namespace=\"default\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "当前任务副本数",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=~\"$deployment\",namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "当前任务云边负载比",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://223.3.94.112:5000/ratio",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "taskName", "value": "${deployment}" }
      ]
     }
    }
   ]
  },
  {
   "title": "当前任务内存用量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container!=\"POD\", pod=~\"$pod\",namespace=\"default\"}) by (pod))/2"
    }
   ]
  },
  {
   "title": "当前任务磁盘用量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container!=\"POD\", pod=~\"$pod\",namespace=\"default\"}) by (pod)"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\",namespace=\"default\"}[1m]))/sum(rate(node_cpu_seconds_total[1m]))*100",
     "legendFormat": "当前任务CPU使用率"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", pod=~\"$pod\", namespace=\"default\"})/sum(node_memory_MemTotal_bytes)*100",
     "legendFormat": "当前任务内存使用率"
    },
    {
     "expr": "sum(container_fs_usage_bytes{container!=\"POD\", pod=~\"$pod\", namespace=\"default\"}) /sum(node_filesystem_size_bytes)*100",
     "legendFormat": "当前任务磁盘使用率"
    }
   ]
  },
  {
   "title": "当前任务CPU用量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"default\"}[1m])) by (pod) / on() group_left() sum(rate(node_cpu_seconds_total[1m]))*100"
    }
   ]
  },
  {
   "title": "微容器内存用量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| project \"values\"\r\n| project \"timestamp\"=unixtime_seconds_todatetime(\"timestamp\"),\"$deployment\"=\"value\"",
     "url": "http://223.3.94.112:5000/containerMemory?taskName=$deployment",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}