{
 "title": "节点感知首页",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "磁盘总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "全局CPU使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=\"master\"}[1m])) - sum(rate(node_cpu_seconds_total{instance=\"master\",mode=\"idle\"}[1m]))) / sum(rate(node_cpu_seconds_total[1m])) * 100",
     "legendFormat": "云节点"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance!=\"master\"}[1m])) - sum(rate(node_cpu_seconds_total{instance!=\"master\",mode=\"idle\"}[1m]))) / sum(rate(node_cpu_seconds_total[1m])) * 100",
     "legendFormat": "边节点"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) / sum(rate(node_cpu_seconds_total[1m])) * 100",
     "legendFormat": "未占用"
    }
   ]
  },
  {
   "title": "总运行时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"master\"} - node_boot_time_seconds{instance=\"master\"}"
    }
   ]
  },
  {
   "title": "CPU总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "全局内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"master\"} - node_memory_MemFree_bytes{instance=\"master\"} - (node_memory_Cached_bytes{instance=\"master\"} + node_memory_Buffers_bytes{instance=\"master\"} + node_memory_SReclaimable_bytes{instance=\"master\"})",
     "legendFormat": "云节点"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance!=\"master\"} - node_memory_MemFree_bytes{instance!=\"master\"} - (node_memory_Cached_bytes{instance!=\"master\"} + node_memory_Buffers_bytes{instance!=\"master\"} + node_memory_SReclaimable_bytes{instance!=\"master\"}))",
     "legendFormat": "边节点"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes + (node_memory_Cached_bytes + node_memory_Buffers_bytes+ node_memory_SReclaimable_bytes))",
     "legendFormat": "未占用"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))/ sum(rate(node_cpu_seconds_total[1m])) ) * 100",
     "legendFormat": "CPU负载"
    },
    {
     "expr": "100 - sum(node_memory_MemFree_bytes + (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes))*100 / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "内存负载"
    },
    {
     "expr": "100 - sum(node_filesystem_avail_bytes) * 100 / sum(node_filesystem_size_bytes)",
     "legendFormat": "磁盘负载"
    }
   ]
  },
  {
   "title": "全局磁盘使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"master\",mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"master\",mountpoint=\"/\"}",
     "legendFormat": "云节点"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance!=\"master\",mountpoint=\"/\"} - node_filesystem_avail_bytes{instance!=\"master\",mountpoint=\"/\"})",
     "legendFormat": "边节点"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=\"/\"})",
     "legendFormat": "未占用"
    }
   ]
  }
 ]
}