{
 "title": "nodeInfo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodeName",
    "label": "节点名称",
    "query": {
     "query": "up{job=\"node-exporter\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "磁盘总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\",instance=\"$nodeName\"})"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$nodeName\"}"
    }
   ]
  },
  {
   "title": "CPU使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=\"$nodeName\"}[1m])) - sum(rate(node_cpu_seconds_total{instance=\"$nodeName\",mode=\"idle\"}[1m]))) / sum(rate(node_cpu_seconds_total{instance=\"$nodeName\"}[1m])) * 100",
     "legendFormat": "节点"
    }
   ]
  },
  {
   "title": "总运行时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$nodeName\"} - node_boot_time_seconds{instance=\"$nodeName\"}"
    }
   ]
  },
  {
   "title": "CPU总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",node=\"$nodeName\"})"
    }
   ]
  },
  {
   "title": "内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$nodeName\"} - node_memory_MemFree_bytes{instance=\"$nodeName\"} - (node_memory_Cached_bytes{instance=\"$nodeName\"} + node_memory_Buffers_bytes{instance=\"$nodeName\"} + node_memory_SReclaimable_bytes{instance=\"$nodeName\"})",
     "legendFormat": "节点"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$nodeName\"}[1m]))/ sum(rate(node_cpu_seconds_total{instance=\"$nodeName\"}[1m])) ) * 100",
     "legendFormat": "CPU负载"
    },
    {
     "expr": "100 - (node_memory_MemFree_bytes{instance=\"$nodeName\"} + (node_memory_Cached_bytes{instance=\"$nodeName\"} + node_memory_Buffers_bytes{instance=\"$nodeName\"} + node_memory_SReclaimable_bytes{instance=\"$nodeName\"}))*100 / node_memory_MemTotal_bytes{instance=\"$nodeName\"}",
     "legendFormat": "内存负载"
    },
    {
     "expr": "100 - sum(node_filesystem_avail_bytes{instance=\"$nodeName\"}) * 100 / sum(node_filesystem_size_bytes{instance=\"$nodeName\"})",
     "legendFormat": "磁盘负载"
    }
   ]
  },
  {
   "title": "磁盘使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$nodeName\",mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"$nodeName\",mountpoint=\"/\"}",
     "legendFormat": "节点"
    }
   ]
  }
 ]
}