{
 "title": "资源感知首页",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "总任务数",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "任务副本数",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "任务内存用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "任务磁盘用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))/sum(rate(node_cpu_seconds_total[1m]))*100",
     "legendFormat": "任务CPU使用率"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"monitoring\"})/sum(node_memory_MemTotal_bytes)*100",
     "legendFormat": "任务内存使用率"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"monitoring\"}) /sum(node_filesystem_size_bytes)*100",
     "legendFormat": "任务磁盘使用率"
    }
   ]
  },
  {
   "title": "任务CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))/sum(rate(node_cpu_seconds_total[1m]))*100"
    }
   ]
  }
 ]
}