apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: device
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30080
  type: NodePort

