apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
    namespace: iot
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;

        server {
            listen 8888;
            location /worker1/command/ {
                proxy_pass http://17.125.10.1:59882/;
            }

            location /worker1/data/ {
                proxy_pass http://17.125.10.1:59880/;
            }

            location /worker1/metadata/ {
                proxy_pass http://17.125.10.1:59881/;
            }

            location /worker2/command/ {
                proxy_pass http://223.26.35.1:59882/;
            }

            location /worker2/data/ {
                proxy_pass http://223.26.35.1:59880/;
            }

            location /worker2/metadata/ {
                proxy_pass http://223.26.35.1:59881/;
            }
        }
    }

