apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-streaming
  namespace: default
spec:
  selector:
    matchLabels:
      app: camera
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: camera
      annotations:
        kubernetes.io/ingress-bandwidth: 3M
        kubernetes.io/egress-bandwidth: 3M
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1
      containers:
      - name: camera
        image: jrottenberg/ffmpeg:latest
        resources:
          requests:
            memory: 50Mi
            cpu: 200m
            ephemeral-storage: 50Mi
          limits:
            memory: 500Mi
            cpu: 1000m
            ephemeral-storage: 1Gi
        #imagePullPolicy: Never
        #command: ["/bin/sh", "-c", "while true; do sleep 2; done;"]
        command: ["/bin/sh", "-c", "ffmpeg -re -stream_loop -1 -i /video/demo.mp4 -c:v copy -c:a copy -f flv rtmp://video-proxy-service.default.svc:1935/live/test"]
        volumeMounts:
          - name: video-source
            mountPath: /video/demo.mp4
          - name: video-dir
            mountPath: /video
      volumes:
        - name: video-source
          hostPath:
            path: /video/demo.mp4
            type: File # target file must exist
        - name: video-dir
          hostPath:
            path: /video
            type: DirectoryOrCreate # target dir not exist then create
